### ISSUE TITLE
[1.21] Flux cells recipe jsons aren't updated to match 1.21 format

### ISSUE THREAD

**Issue by WhitePhant0m** [GregTech-Exploring-Pioneer/BiggerAE2#12]
They don't have recipes when AppFlux is installed.

**Comment by DancingSnow0517** [comment]
When I port to 1.21, appflux had not been updated yet, so may have some problem in that

**Comment by DancingSnow0517** [comment]
already fix it, you can update mod from curseforge or modrinth in some minite
