### ISSUE TITLE
crash due to ldlib library

### ISSUE THREAD

**Issue by SunIAver** [GregTech-Exploring-Pioneer/BiggerAE2#14]
Bigger AE2 v1.20.1-1.3.4

jei updated these days and there is a problem with ldlib as reported in the link below

https://github.com/Low-Drag-MC/LDLib-Architectury/issues/29

**Comment by DancingSnow0517** [comment]
I forgot to clear my Jarjar dependencies, my mod doesn't actually need it

**Comment by DancingSnow0517** [comment]
i push fix, you can download it in some minuit
