### ISSUE TITLE
Crash with Cuisine Delight

### ISSUE THREAD

**Issue by WhitePhant0m** [GregTech-Exploring-Pioneer/BiggerAE2#17]
Sorry if this isn't the correct place to report this to, but I wasn't entirely sure which mod to report this to, so I reported to both.
Crash occurs when Cuisine Delight and BiggerAE2 are both present in an instance.
Both mods work fine when the other isn't present.

[latest.log](https://mclo.gs/gYMHJJZ)
[crash log](https://mclo.gs/Ld4l68A)

https://github.com/Minecraft-LightLand/Cuisine-Delight/issues/10

**Comment by DancingSnow0517** [comment]
i think it may cause by use different registrate fork

**Comment by lcy0x1** [comment]
> i think it may cause by use different registrate fork

1.4.8 is the same as 1.3.0+49. I merged it into IThundxr later.
In CuisineDelight 1.2.1 I switched to 1.3.0+50. Hope that works

**Comment by DancingSnow0517** [comment]
> > i think it may cause by use different registrate fork
> 
> 1.4.8 is the same as 1.3.0+49. I merged it into IThundxr later. In CuisineDelight 1.2.1 I switched to 1.3.0+50. Hope that works

my version is 1.3.0+16, i will try to update it.

**Comment by DancingSnow0517** [comment]
i have no idea why my mod will crash in registrate 1.3.0+50

**Comment by lcy0x1** [comment]
Do you need help with it?

**Comment by lcy0x1** [comment]
In `BlockEntityType#274`:

```
private final Holder.Reference<BlockEntityType<?>> builtInRegistryHolder = 
BuiltInRegistries.BLOCK_ENTITY_TYPE.createIntrusiveHolder(this);
```

Check if this line is called.

**Comment by DancingSnow0517** [comment]
oh, i already fixed it.

**Comment by DancingSnow0517** [comment]
i pushed new version 1.4.2, can check it on curseforge in some minuts

**Comment by WhitePhant0m** [comment]
1.4.2 seems to fix it, thanks!
