### ISSUE TITLE
Invalid integer string in storage cell NBT crashes the game on hover

### ISSUE THREAD

**Issue by James103** [GregTech-Exploring-Pioneer/BiggerAE2#21]
When NBT data is entered into a `/give` command or a Pipez item filter GUI which causes the `count` variable to be unable to be parsed as an integer, the game will crash with `java.lang.NumberFormatException: For input string: "___"` with the invalid integer string filled in the blank, here:
https://github.com/DancingSnow0517/BiggerAE2/blob/3cabf18a975d926128c2a80285dc8f9c519ccfce/src/main/java/cn/dancingsnow/bigger_ae2/item/cell/DigitalSingularityStorageCell.java#L46

To reproduce, type the following NBT data into a Pipez item filter GUI and pass in `bigger_ae2:digital_singularity_fluid_storage_cell` as the item to be filtered:
```
{"ae2:storage_cell_config_inv":[{"#":0L,"#t":"ae2:f",id:"water"}],"bigger_ae2:singularity_storage":{count:"___",key:{"#t":"ae2:f",id:"water"}}}
```
The game will then crash as described above.

Would it be possible to catch this error (invalid count) and gracefully handle it (by marking the cell invalid or clearing the contents) rather than crashing the game?

**Comment by DancingSnow0517** [comment]
Of course, I forgot to consider giving custom NBT

**Comment by DancingSnow0517** [comment]
new release pushed, you can check it in curseforge in some minutes
